---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: portainer-pv
  namespace: portainer 
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain 
  local:
    path: /DATA1 
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - {key: kubernetes.io/hostname, operator: In, values: [k8s-worker-01]}
